apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: event-metrics
    app.kubernetes.io/version: 1.0.0
  name: event-metrics
  namespace: kubediag
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: event-metrics
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: event-metrics
        app.kubernetes.io/version: 1.0.0
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - image: hub.c.163.com/kubediag/event-metrics:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            name: http-metrics
        name: event-metrics
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 800Mi
          requests:
            cpu: 100m
            memory: 500Mi
      serviceAccountName: event-metrics
      terminationGracePeriodSeconds: 10
