apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: event-metrics
    app.kubernetes.io/version: 1.0.0
  name: event-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: event-metrics
subjects:
- kind: ServiceAccount
  name: event-metrics
  namespace: kubediag
